services:
  postgres:
    container_name: postgres_bank
    image: postgres:17.2
    environment:
      POSTGRES_DB: bankdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bank-network
    restart: unless-stopped

  app:
    build:
       context: .
       dockerfile: Dockerfile
    image: bank-api:latest
    container_name: bank-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bankdb
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
    depends_on:
      - postgres
    networks:
      - bank-network

networks:
    bank-network:
      driver: bridge

volumes:
  postgres_data: