services:
  postgres:
    container_name: postgres_bank
    image: postgres:17.2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bankcardsdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: no

networks:
    postgres:
      driver: bridge

volumes:
  postgres-data: