services:
  postgres:
    container_name: postgres_bank
    image: postgres:17.2
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: bankdb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - bank-network
    restart: unless-stopped

#  app:
#    build: .
#    container_name: bankapp
#    restart: always
#    ports:
#      - "8080:8080"
#    environment:
#      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/springapp
#      SPRING_DATASOURCE_USERNAME: springuser
#      SPRING_DATASOURCE_PASSWORD: springpass
#    depends_on:
#      - postgres
#    networks:
#      - spring-network

networks:
    bank-network:
      driver: bridge

volumes:
  postgres_data: