server:
  port: 8080

spring:
  application:
    name: bankcards

  datasource:
    url: jdbc:postgresql://localhost:5432/bankdb
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none   # options: none, validate, update, create, create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changelog-master.yml

# Logging
logging:
  level:
    com.example: DEBUG
    org.springframework.security: DEBUG
    liquibase: INFO

# Swagger/OpenAPI Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method

# JWT Configuration
jwt:
  secret: 93ee8fde0d73e1dd3daa7e93d6d5613c7e17f43b6752dc300c64eca4f006af13
  expirationMs: 86400000 # 24 hours in milliseconds
